import type { LegalQuestionDefinitionV2 } from "@/types/legalQuestion";

const positions = [
  { key: "criminal-law.offense-structure.elements", label: "構成要件該當性" },
  { key: "criminal-law.offense-structure.unlawfulness", label: "違法性" },
  { key: "criminal-law.offense-structure.culpability", label: "有責性" },
];

const base = {
  subjectKey: "criminal-law",
  origin: "user-authored" as const,
  reviewStatus: "draft" as const,
  primaryChapterRef: "criminal-law.offense-structure",
  chapterRefs: ["criminal-law.offense-structure"],
  predictionChoices: positions,
  termRefs: ["offense-structure"],
  sourceRefs: ["source.phoenix.sample"],
  examName: "Phoenix 刑法樣板題",
  paperCode: "VERTICAL-SLICE",
  lawVersion: "sample-2026-07",
  negativeStem: false,
  generationProfile: "phoenix-legal-v2-sample",
};

export const legalQuestionSeeds: LegalQuestionDefinitionV2[] = [
  {
    ...base,
    key: "criminal-law.sample.three-levels-order",
    prompt: "以犯罪成立三階層檢驗一個行為時，下列判斷順序何者最適當？",
    options: [
      { key: "a", text: "有責性 → 違法性 → 構成要件該當性" },
      { key: "b", text: "違法性 → 構成要件該當性 → 有責性" },
      { key: "c", text: "構成要件該當性 → 違法性 → 有責性" },
      { key: "d", text: "構成要件該當性 → 有責性 → 違法性" },
    ],
    answerRevisions: [{
      id: "answer.original",
      correctOptionKeys: ["c"],
      status: "original",
      sourceRef: "source.phoenix.sample",
      effectiveAt: "2026-07-17T00:00:00.000Z",
    }],
    primaryIssueRef: "criminal-law.offense-structure.elements",
    issueRefs: positions.map((item) => item.key),
    questionSignals: ["判斷順序", "犯罪成立三階層"],
    reasoningSteps: [
      "先問行為是否落入刑罰規範描述的構成要件。",
      "該當構成要件後，再檢查是否有正當化事由阻卻違法。",
      "最後判斷行為人是否具有可責性。",
    ],
    optionAnalyses: [
      { optionKey: "a", verdict: "incorrect", rule: "三階層不是從責任倒推。", errorPoint: "把行為人的可責性放在行為該當性的前面。", minimalCorrection: "先構成要件，再違法性，最後有責性。", sourceRefs: [] },
      { optionKey: "b", verdict: "incorrect", rule: "違法性判斷以構成要件該當為前提。", errorPoint: "尚未確認構成要件就先判斷違法。", minimalCorrection: "把構成要件該當性移到第一層。", sourceRefs: [] },
      { optionKey: "c", verdict: "correct", rule: "固定順序是構成要件該當性、違法性、有責性。", sourceRefs: [] },
      { optionKey: "d", verdict: "incorrect", rule: "有責性在違法性之後。", errorPoint: "把責任判斷提早。", minimalCorrection: "違法性應在有責性之前。", sourceRefs: [] },
    ],
    commonTraps: ["先看到行為人年齡或精神狀態，就跳過前兩層直接談責任。"],
    microLessonRefs: ["criminal-law.offense-structure.framework"],
    questionNumber: 1,
  },
  {
    ...base,
    key: "criminal-law.sample.self-defense-position",
    prompt: "行為已符合某罪構成要件，接著主張正當防衛。此主張原則上應先放在哪一層檢驗？",
    options: [
      { key: "a", text: "客觀構成要件" },
      { key: "b", text: "主觀構成要件" },
      { key: "c", text: "違法性" },
      { key: "d", text: "有責性" },
    ],
    answerRevisions: [{ id: "answer.original", correctOptionKeys: ["c"], status: "original", sourceRef: "source.phoenix.sample", effectiveAt: "2026-07-17T00:00:00.000Z" }],
    primaryIssueRef: "criminal-law.offense-structure.unlawfulness",
    issueRefs: positions.map((item) => item.key),
    questionSignals: ["符合構成要件", "正當防衛", "哪一層"],
    reasoningSteps: ["題目已確認構成要件該當。", "正當防衛是正當化事由，應轉入違法性層。"],
    optionAnalyses: [
      { optionKey: "a", verdict: "incorrect", rule: "題目已給定構成要件該當。", minimalCorrection: "進入違法性檢查正當防衛。", sourceRefs: [] },
      { optionKey: "b", verdict: "incorrect", rule: "正當防衛不是故意等主觀構成要件。", minimalCorrection: "放到違法性層。", sourceRefs: [] },
      { optionKey: "c", verdict: "correct", rule: "正當防衛原則上在違法性層檢驗。", sourceRefs: [] },
      { optionKey: "d", verdict: "incorrect", rule: "有責性處理可責性，不是正當化事由。", minimalCorrection: "放到違法性層。", sourceRefs: [] },
    ],
    commonTraps: ["看到防衛人受到威脅就直接談責任減免。"],
    microLessonRefs: ["criminal-law.offense-structure.unlawfulness"],
    questionNumber: 2,
  },
  {
    ...base,
    key: "criminal-law.sample.capacity-position",
    prompt: "題目問行為人是否具有責任能力，最直接對應犯罪成立三階層中的哪一層？",
    options: [
      { key: "a", text: "構成要件該當性" },
      { key: "b", text: "違法性" },
      { key: "c", text: "有責性" },
      { key: "d", text: "客觀處罰條件" },
    ],
    answerRevisions: [{ id: "answer.original", correctOptionKeys: ["c"], status: "original", sourceRef: "source.phoenix.sample", effectiveAt: "2026-07-17T00:00:00.000Z" }],
    primaryIssueRef: "criminal-law.offense-structure.culpability",
    issueRefs: positions.map((item) => item.key),
    questionSignals: ["責任能力", "哪一層"],
    reasoningSteps: ["先辨識題目直接問的是行為人的可責性。", "責任能力屬於有責性層的核心問題。"],
    optionAnalyses: [
      { optionKey: "a", verdict: "incorrect", rule: "責任能力不是行為構成要件。", sourceRefs: [] },
      { optionKey: "b", verdict: "incorrect", rule: "責任能力不是阻卻違法事由。", sourceRefs: [] },
      { optionKey: "c", verdict: "correct", rule: "責任能力在有責性層判斷。", sourceRefs: [] },
      { optionKey: "d", verdict: "incorrect", rule: "客觀處罰條件與責任能力不是同一分類。", sourceRefs: [] },
    ],
    commonTraps: ["只看到能力二字，就誤放進構成要件主體資格。"],
    microLessonRefs: ["criminal-law.offense-structure.culpability"],
    questionNumber: 3,
  },
  {
    ...base,
    key: "criminal-law.sample.intent-position",
    prompt: "一般故意犯中的故意，主要應在犯罪成立三階層的哪個位置處理？",
    options: [
      { key: "a", text: "主觀構成要件" },
      { key: "b", text: "違法性" },
      { key: "c", text: "有責性" },
      { key: "d", text: "刑罰效果" },
    ],
    answerRevisions: [{ id: "answer.original", correctOptionKeys: ["a"], status: "original", sourceRef: "source.phoenix.sample", effectiveAt: "2026-07-17T00:00:00.000Z" }],
    primaryIssueRef: "criminal-law.offense-structure.elements",
    issueRefs: positions.map((item) => item.key),
    questionSignals: ["故意犯", "故意", "位置"],
    reasoningSteps: ["先區分題目問的是構成要件故意，還是責任層的其他問題。", "一般故意犯的故意屬主觀構成要件。"],
    optionAnalyses: [
      { optionKey: "a", verdict: "correct", rule: "故意是一般故意犯的主觀構成要件。", sourceRefs: [] },
      { optionKey: "b", verdict: "incorrect", rule: "違法性層處理正當化事由。", sourceRefs: [] },
      { optionKey: "c", verdict: "incorrect", rule: "有責性不取代構成要件故意的定位。", sourceRefs: [] },
      { optionKey: "d", verdict: "incorrect", rule: "刑罰效果在犯罪成立判斷之後。", sourceRefs: [] },
    ],
    commonTraps: ["把所有主觀心理狀態都丟進有責性。"],
    microLessonRefs: ["criminal-law.offense-structure.subjective-elements"],
    questionNumber: 4,
  },
  {
    ...base,
    key: "criminal-law.sample.three-levels-order-variant",
    prompt: "某行為已該當構成要件且沒有阻卻違法事由，下一步最適合檢查什麼？",
    options: [
      { key: "a", text: "重新檢查客觀構成要件" },
      { key: "b", text: "行為人的有責性" },
      { key: "c", text: "直接宣告成立犯罪" },
      { key: "d", text: "先決定刑罰種類" },
    ],
    answerRevisions: [{ id: "answer.original", correctOptionKeys: ["b"], status: "original", sourceRef: "source.phoenix.sample", effectiveAt: "2026-07-17T00:00:00.000Z" }],
    primaryIssueRef: "criminal-law.offense-structure.culpability",
    issueRefs: positions.map((item) => item.key),
    questionSignals: ["已該當", "沒有阻卻違法", "下一步"],
    reasoningSteps: ["題目已完成第一層與第二層。", "接著檢查第三層有責性。"],
    optionAnalyses: [
      { optionKey: "a", verdict: "incorrect", rule: "題目已確認構成要件該當。", sourceRefs: [] },
      { optionKey: "b", verdict: "correct", rule: "前兩層通過後，接著判斷有責性。", sourceRefs: [] },
      { optionKey: "c", verdict: "incorrect", rule: "仍需完成有責性判斷。", sourceRefs: [] },
      { optionKey: "d", verdict: "incorrect", rule: "刑罰效果不是三階層的下一步。", sourceRefs: [] },
    ],
    commonTraps: ["把違法性通過誤當成犯罪已完整成立。"],
    microLessonRefs: ["criminal-law.offense-structure.framework"],
    variantOf: "criminal-law.sample.three-levels-order",
    questionNumber: 5,
  },
];

export const legalSessionSeedQuestionKeys = legalQuestionSeeds.filter((question) => !question.variantOf).map((question) => question.key);
