/* AIAP Battle Rose Edition - Chapter Boss quiz bank. */
(function(){
  const DIFFICULTIES=['easy','easy','easy','easy','easy','easy','medium','medium','medium','medium','medium','medium','medium','medium','hard','hard','hard','hard','hard','hard'];
  const CHAPTERS=[
    {chapterId:'ch03',chapterTitle:'Ch03 任務判斷',bossName:'任務判斷獸',badge:'任務刀',tag:'任務判斷',pool:['分類','回歸','分群','降維','異常偵測','時間序列','推薦排序','強化學習'],topics:[
      ['判斷顧客是否流失，輸出是會 / 不會','分類','分類 vs 回歸','把二元標籤誤當連續數值'],
      ['預測下月銷售金額，輸出是數字','回歸','分類 vs 回歸','看到預測就直接選分類'],
      ['沒有標籤，要把會員依行為自然分組','分群','分類 vs 分群','把無標籤分群當成分類'],
      ['把 500 個特徵壓成少數主成分','降維','降維','把降維誤解成刪除資料列'],
      ['找出刷卡行為中極少見的可疑交易','異常偵測','異常偵測','把少數類別問題都當異常偵測'],
      ['預測每日來客量並保留時間順序','時間序列','時間序列','打亂時間資料再驗證'],
      ['根據使用者偏好排序商品','推薦排序','任務判斷','只看模型名稱不看輸出'],
      ['系統透過獎勵學會最佳操作策略','強化學習','任務判斷','把有回饋就當監督式學習'],
      ['醫療影像判斷良性或惡性','分類','分類 vs 回歸','忽略類別不平衡造成的指標陷阱'],
      ['估計房價與坪數、地段的關係','回歸','分類 vs 回歸','把價格分級後忘了原始目標是連續值'],
      ['探索文件主題但沒有預先定義類別','分群','分類 vs 分群','把主題探索當已知類別分類'],
      ['視覺化高維資料到 2D 平面','降維','降維','把視覺化結果當最終預測'],
      ['機台感測值突然偏離歷史型態','異常偵測','異常偵測','只用平均值忽略尾端風險'],
      ['預測每小時用電量','時間序列','時間序列','隨機切分導致未來資訊外洩'],
      ['客服文本要判斷正負情緒','分類','情感分析','把摘要任務誤當分類任務'],
      ['找出顧客旅程中的自然族群','分群','分類 vs 分群','先替群組貼標籤再訓練'],
      ['交易風險分數是 0 到 1 連續值','回歸','分類 vs 回歸','把分數輸出硬切成分類'],
      ['壓縮特徵後再交給下游模型','降維','PCA vs 特徵選擇','混淆特徵選擇與特徵投影'],
      ['少數攻擊樣本未知且型態會變','異常偵測','異常偵測','硬建立固定攻擊類別'],
      ['依序列狀態決定下一步行動','強化學習','任務判斷','忽略獎勵與策略'] ]},
    {chapterId:'ch05',chapterTitle:'Ch05 資料前處理',bossName:'資料陷阱師',badge:'資料梳理梳',tag:'資料前處理',pool:['One-hot Encoding','Label Encoding','標準化','正規化','正則化','缺失值補值','離群值處理','資料洩漏','Robust Scaling','SMOTE'],topics:[
      ['無序城市欄位要轉成模型可讀格式','One-hot Encoding','One-hot vs Label Encoding','把城市編成 1、2、3 造成假順序'],
      ['會員等級本身有低中高順序','Label Encoding','One-hot vs Label Encoding','所有類別都盲目 one-hot'],
      ['距離型模型受量綱影響','標準化','標準化 vs 正規化 vs 正則化','把特徵縮放和防過擬合混在一起'],
      ['影像像素需要壓到 0 到 1','正規化','標準化 vs 正規化 vs 正則化','誤把 min-max scaling 叫正則化'],
      ['模型太複雜，需要懲罰係數','正則化','標準化 vs 正規化 vs 正則化','把 regularization 當 normalization'],
      ['欄位缺失不是隨機，與客群有關','缺失值補值','缺失值','直接刪除導致樣本偏誤'],
      ['極端交易金額影響平均與標準差','離群值處理','離群值','一律刪除所有極端值'],
      ['先用全資料做標準化再切訓練測試','資料洩漏','資料洩漏','前處理偷看測試資料'],
      ['資料有極端值但仍需縮放','Robust Scaling','Robust Scaling','使用 Min-Max 被極端值拉歪'],
      ['詐欺樣本太少導致模型偏向多數類','SMOTE','類別不平衡','只看 Accuracy 誤判效果很好'],
      ['國家代碼無大小關係','One-hot Encoding','One-hot vs Label Encoding','把無序類別編出距離'],
      ['教育程度可自然排序','Label Encoding','One-hot vs Label Encoding','忽略序位資訊'],
      ['SVM/KNN 特徵尺度差異很大','標準化','標準化 vs 正規化 vs 正則化','讓大尺度特徵主宰距離'],
      ['神經網路輸入需穩定在固定範圍','正規化','標準化 vs 正規化 vs 正則化','未縮放造成收斂不穩'],
      ['LASSO 想做稀疏特徵','正則化','LASSO / L1','把 L1 當資料清洗'],
      ['平均補值會扭曲偏態分布','缺失值補值','缺失值','不看缺失機制就補平均'],
      ['箱型圖顯示高端異常點','離群值處理','離群值','不知道業務上是否真異常'],
      ['特徵工程用了未來才知道的欄位','資料洩漏','資料洩漏','訓練時使用未來資訊'],
      ['薪資資料長尾明顯','Robust Scaling','Robust Scaling','標準化被長尾影響'],
      ['少數類過採樣後訓練分數暴增','SMOTE','類別不平衡','在切分前過採樣造成洩漏'] ]},
    {chapterId:'ch07',chapterTitle:'Ch07 評估指標',bossName:'指標審判官',badge:'指標戒指',tag:'評估指標',pool:['Accuracy','Precision','Recall','F1','ROC-AUC','PR-AUC','RMSE','MAE','Calibration','Confusion Matrix'],topics:[
      ['錯抓正常信件成本高，要減少誤判為垃圾','Precision','Precision vs Recall','只追召回導致誤殺太多'],
      ['漏掉癌症病例成本高','Recall','Precision vs Recall','只看精確率忽略漏診'],
      ['類別均衡且錯誤成本相近','Accuracy','Accuracy 陷阱','在不平衡資料仍只看 Accuracy'],
      ['Precision 與 Recall 都要兼顧','F1','F1','只報其中一個指標'],
      ['比較不同閾值下二元分類排序能力','ROC-AUC','ROC-AUC / PR-AUC','把 AUC 當固定閾值正確率'],
      ['正類極少且關心抓到正類品質','PR-AUC','ROC-AUC / PR-AUC','不平衡資料仍迷信 ROC-AUC'],
      ['房價預測大誤差要懲罰更重','RMSE','RMSE vs MAE','忽略平方誤差放大極端值'],
      ['預測誤差要較不受極端值影響','MAE','RMSE vs MAE','把 MAE 當會懲罰大錯'],
      ['機率分數是否可信很重要','Calibration','Calibration','只看排序不看機率校準'],
      ['需要拆 TP/FP/FN/TN','Confusion Matrix','Confusion Matrix','只看單一總分無法定位錯誤'],
      ['推薦系統假陽性讓使用者反感','Precision','Precision vs Recall','忽略誤推薦成本'],
      ['詐欺偵測寧可多查也不能漏','Recall','Precision vs Recall','把低漏抓率誤當高精確率'],
      ['資料 99% 都是正常','Accuracy','Accuracy 陷阱','全猜正常也有高 Accuracy'],
      ['模型調參時需要平衡查全與查準','F1','F1','資料極不平衡仍不看 PR 曲線'],
      ['模型分數排序而非單點閾值','ROC-AUC','ROC-AUC / PR-AUC','把曲線下面積當業務收益'],
      ['少數正例檢索任務','PR-AUC','ROC-AUC / PR-AUC','正類稀少時 ROC 過度樂觀'],
      ['庫存量預測不想容忍大爆錯','RMSE','RMSE vs MAE','沒有檢查離群誤差'],
      ['外送時間預測有少數塞車極端值','MAE','RMSE vs MAE','讓少數極端主導指標'],
      ['信用風險分數要對應真實違約率','Calibration','Calibration','高 AUC 但機率不可用'],
      ['要知道模型錯在哪一類','Confusion Matrix','Confusion Matrix','只看平均分數'] ]},
    {chapterId:'ch06',chapterTitle:'Ch06 模型選擇',bossName:'模型選擇獸',badge:'模型刀鞘',tag:'模型選擇',pool:['線性回歸','邏輯斯回歸','決策樹','隨機森林','KNN','K-means','SVM','PCA','DBSCAN','LASSO'],topics:[
      ['預測連續銷售額並要求可解釋係數','線性回歸','線性回歸 vs 邏輯斯回歸','把連續目標丟給分類模型'],
      ['預測是否違約，輸出機率','邏輯斯回歸','線性回歸 vs 邏輯斯回歸','用線性回歸處理二元分類'],
      ['需要可視化規則與切分條件','決策樹','模型選擇','只追高分忽略可解釋需求'],
      ['多棵樹降低單棵樹變異','隨機森林','Random Forest vs Boosting','把 bagging 與 boosting 混淆'],
      ['依鄰近樣本投票分類','KNN','KNN vs K-means','把 KNN 當分群'],
      ['沒有標籤要找 K 個群中心','K-means','KNN vs K-means','把 K-means 當分類器'],
      ['高維小樣本且需要最大間隔','SVM','SVM','忘記特徵縮放'],
      ['降低維度並保留主要變異','PCA','PCA vs 特徵選擇','以為 PCA 只是挑原始欄位'],
      ['群形狀不規則且有雜訊','DBSCAN','DBSCAN','硬指定 K 值'],
      ['想要特徵係數稀疏','LASSO','LASSO / L1','混淆 L1 與 L2'],
      ['房價與面積近似線性','線性回歸','線性回歸 vs 邏輯斯回歸','不檢查殘差'],
      ['顧客會不會流失','邏輯斯回歸','線性回歸 vs 邏輯斯回歸','把機率閾值誤當模型本身'],
      ['信用審核要能說出規則','決策樹','模型選擇','忽略過深樹過擬合'],
      ['表格資料需要穩健基準模型','隨機森林','Random Forest vs Boosting','單棵樹不穩定'],
      ['資料量小且局部相似性重要','KNN','KNN vs K-means','忽略距離尺度'],
      ['市場區隔沒有既有標籤','K-means','分類 vs 分群','先定義類別再分群'],
      ['文字特徵高維稀疏','SVM','SVM','未調 kernel 與 C'],
      ['視覺化多變數資料','PCA','PCA vs 特徵選擇','把投影結果直接解釋為原特徵'],
      ['地理熱點群聚且群數未知','DBSCAN','DBSCAN','DBSCAN 對參數 eps 敏感'],
      ['高維迴歸想自動壓掉無用特徵','LASSO','LASSO / L1','正則化強度未驗證'] ]},
    {chapterId:'ch08',chapterTitle:'Ch08 深度學習 / Transformer',bossName:'注意力魔王',badge:'注意力水晶',tag:'深度學習',pool:['CNN','RNN/LSTM','Transformer','Self-attention','BERT','GPT','Word2Vec / GloVe','TF-IDF','N-gram','CLIP'],topics:[
      ['影像局部紋理與邊緣辨識','CNN','CNN / Object Detection','把影像任務直接用表格模型'],
      ['序列資料需要保留時間依賴','RNN/LSTM','Transformer / Self-Attention','忽略長距依賴'],
      ['長篇文本翻譯需平行捕捉語境','Transformer','Transformer / Self-Attention','把注意力當卷積'],
      ['每個 token 依內容加權其他 token','Self-attention','Transformer / Self-Attention','只看鄰近詞'],
      ['雙向上下文做理解型任務','BERT','BERT / MLM','把 BERT 當自回歸生成器'],
      ['自回歸生成下一個 token','GPT','BERT vs GPT','把 GPT 當遮罩語言模型'],
      ['靜態詞向量表徵詞語語意','Word2Vec / GloVe','Word2Vec / GloVe','以為一定有上下文動態語意'],
      ['用詞頻與逆文件頻率做關鍵字權重','TF-IDF','TF-IDF','無法理解語意等價'],
      ['只根據固定長度前文估機率','N-gram','N-gram','難捕捉長距語意'],
      ['圖文共同嵌入做跨模態檢索','CLIP','CLIP / 多模態','把多模態當純文字分類'],
      ['物件偵測需定位邊界框','CNN','CNN / Object Detection','只做影像分類無法定位'],
      ['股價序列輸入有前後順序','RNN/LSTM','Transformer / Self-Attention','隨機打亂序列'],
      ['客服長文摘要要理解遠距詞關係','Transformer','Transformer / Self-Attention','N-gram 片段合理但整體不連貫'],
      ['注意力權重連接查詢與上下文','Self-attention','Transformer / Self-Attention','把權重當人工規則'],
      ['MLM 隨機遮罩預測','BERT','BERT / MLM','由左到右生成是 GPT'],
      ['聊天模型逐步生成答案','GPT','BERT vs GPT','雙向 encoder 不等於生成 decoder'],
      ['比較詞語相似度但不看句子上下文','Word2Vec / GloVe','Word2Vec / GloVe','一詞多義處理不足'],
      ['法律文件搜尋用字面關鍵詞','TF-IDF','TF-IDF','同義詞召回不足'],
      ['客服句子片段合理但跨句失焦','N-gram','N-gram','固定窗口太短'],
      ['用圖片找相關文字描述','CLIP','CLIP / 多模態','未建立共同向量空間'] ]},
    {chapterId:'ch09-rag',chapterTitle:'Ch09 RAG',bossName:'RAG 多頭蛇',badge:'RAG 封印章',tag:'RAG',pool:['RAG','Chunking','Embedding','Vector Database','Retriever','Reranker','Grounding','Citation','Prompt Injection','Guardrails'],topics:[
      ['答案需查公司最新內規而非靠模型記憶','RAG','RAG vs Fine-tuning','把知識更新問題拿去微調'],
      ['文件切段太長導致檢索雜訊','Chunking','Chunking','切塊不看語意邊界'],
      ['把文字轉成可比對語意的向量','Embedding','Embedding vs Vector Database','把 embedding 當資料庫'],
      ['儲存向量並做相似搜尋','Vector Database','Embedding vs Vector Database','把向量庫當生成模型'],
      ['從知識庫找候選段落','Retriever','Retriever vs Reranker','把檢索與重排混在一起'],
      ['對候選文件重新排序提升相關性','Reranker','Retriever vs Reranker','只增加 top-k 不改善排序'],
      ['回答必須立基於取回文件','Grounding','Grounding vs Citation','引用格式不等於有根據'],
      ['回答附上來源段落或文件位置','Citation','Grounding vs Citation','有引用但引用不支撐答案'],
      ['使用者要求忽略規則洩漏系統提示','Prompt Injection','Prompt Injection vs Guardrails','把攻擊當正常 prompt'],
      ['限制工具與輸出避免越權','Guardrails','Prompt Injection vs Guardrails','只靠模型自覺安全'],
      ['法規頻繁更新的客服問答','RAG','RAG vs Fine-tuning','把新資料背進參數'],
      ['表格段落切斷造成上下文遺失','Chunking','Chunking','固定字數切壞語意'],
      ['語意相似搜尋前的向量化步驟','Embedding','Embedding vs Vector Database','搜尋引擎不是 embedding 本身'],
      ['需要近似最近鄰查詢','Vector Database','Embedding vs Vector Database','忽略索引與距離度量'],
      ['第一階段召回不足','Retriever','Retriever vs Reranker','重排無法救回沒召回的文件'],
      ['候選太多且相似度粗糙','Reranker','Retriever vs Reranker','把 reranker 當資料來源'],
      ['模型回答不得超出資料內容','Grounding','Grounding vs Citation','胡編後再補引用'],
      ['稽核要求能追到來源','Citation','Grounding vs Citation','只貼文件名沒有段落依據'],
      ['惡意文件內藏請忽略上文','Prompt Injection','Prompt Injection vs Guardrails','檢索內容也可能有攻擊'],
      ['限制私人資料不可被工具取出','Guardrails','Prompt Injection vs Guardrails','權限未最小化'] ]},
    {chapterId:'ch09-agent',chapterTitle:'Ch09 Agent / Fine-tuning / LoRA',bossName:'代理協定獸',badge:'代理鑰匙',tag:'Agent',pool:['Fine-tuning','LoRA / PEFT','RLHF','Tool Calling','Agent','MCP','A2A','Prompt Engineering','RAG','函式呼叫'],topics:[
      ['固定語氣與格式要長期內化','Fine-tuning','RAG vs Fine-tuning','拿微調更新外部知識'],
      ['低成本微調少量參數','LoRA / PEFT','LoRA / PEFT','把 LoRA 當完整重訓'],
      ['用人類偏好調整回覆品質','RLHF','RLHF','把 RLHF 當資料檢索'],
      ['模型按 schema 呼叫天氣 API','Tool Calling','Tool Calling','把工具結果當模型記憶'],
      ['模型能規劃多步驟並使用工具','Agent','Tool Calling','單次函式呼叫不一定是 Agent'],
      ['連接模型與外部工具資源的協定','MCP','MCP vs A2A','把 MCP 當代理彼此溝通'],
      ['不同代理之間協作溝通','A2A','MCP vs A2A','把 A2A 當工具介面'],
      ['只改提示詞不改模型參數','Prompt Engineering','RAG vs Fine-tuning','把 prompt 當可更新知識庫'],
      ['查文件回答最新制度','RAG','RAG vs Fine-tuning','把最新知識塞進微調'],
      ['嚴格 JSON 輸出呼叫函式','函式呼叫','Tool Calling','自由文字解析不穩'],
      ['客服品牌語氣一致','Fine-tuning','RAG vs Fine-tuning','過度微調造成遺忘'],
      ['用 adapter 快速適配任務','LoRA / PEFT','LoRA / PEFT','更新全部權重成本太高'],
      ['偏好安全且有幫助的答案','RLHF','RLHF','以為能保證事實正確'],
      ['訂單查詢需要呼叫資料庫','Tool Calling','Tool Calling','模型不能憑空知道訂單狀態'],
      ['訂旅程需查航班、比較、下單','Agent','Tool Calling','沒有邊界會亂用工具'],
      ['工具 catalog 提供給模型','MCP','MCP vs A2A','協定不是單一產品功能'],
      ['兩個代理交接任務狀態','A2A','MCP vs A2A','混淆工具與代理協調'],
      ['考題要求改善回答格式','Prompt Engineering','RAG vs Fine-tuning','用 RAG 解格式問題'],
      ['內部知識庫常變','RAG','RAG vs Fine-tuning','每次變更都重訓'],
      ['函式參數需可驗證','函式呼叫','Tool Calling','讓模型自由拼 URL'] ]},
    {chapterId:'ch12',chapterTitle:'Ch12 MLOps',bossName:'部署監控獸',badge:'部署徽記',tag:'MLOps',pool:['Model Registry','Canary Deployment','Shadow Deployment','Data Drift','Concept Drift','Rollback','Monitoring','CI/CD','Training-serving Skew','Auto Scaling'],topics:[
      ['需要管理模型版本、階段與審批','Model Registry','Model Registry','只把檔案丟資料夾'],
      ['少量真實流量先導入新版','Canary Deployment','Canary vs Shadow','一次全量上線風險高'],
      ['新版只旁路接收流量不影響使用者','Shadow Deployment','Canary vs Shadow','把 shadow 當真正服務回應'],
      ['輸入特徵分布改變','Data Drift','Data Drift vs Concept Drift','把資料分布變化當標籤關係變化'],
      ['X 與 y 關係改變','Concept Drift','Data Drift vs Concept Drift','只監控輸入分布不夠'],
      ['新版出錯需回到上一版','Rollback','Rollback / Monitoring','沒有保存可回復版本'],
      ['持續追蹤延遲、錯誤率與指標','Monitoring','Monitoring','部署後不監控'],
      ['訓練測試部署流程自動化','CI/CD','CI/CD','手動複製模型造成不一致'],
      ['訓練特徵與線上特徵計算不同','Training-serving Skew','Training-serving Skew','離線線上邏輯不一致'],
      ['流量暴增時自動增加資源','Auto Scaling','Auto Scaling','只提高模型複雜度'],
      ['模型進入 staging 前要記錄 lineage','Model Registry','Model Registry','版本不可追溯'],
      ['新推薦模型先給 5% 使用者','Canary Deployment','Canary vs Shadow','沒有分批觀察'],
      ['信用模型新版先離線旁路比較','Shadow Deployment','Canary vs Shadow','shadow 不該改變決策'],
      ['節慶期間使用者年齡分布變了','Data Drift','Data Drift vs Concept Drift','以為一定要重訓'],
      ['詐欺手法改變導致舊特徵失效','Concept Drift','Data Drift vs Concept Drift','只看 PSI 不看標籤效果'],
      ['部署後錯誤率升高要快速撤回','Rollback','Rollback / Monitoring','無回復計畫'],
      ['監控模型分數與業務 KPI','Monitoring','Monitoring','只看伺服器 CPU'],
      ['每次提交自動測試資料 schema','CI/CD','CI/CD','資料契約沒檢查'],
      ['訓練用平均補值，線上用 0 補值','Training-serving Skew','Training-serving Skew','同名欄位不代表同邏輯'],
      ['尖峰流量維持服務可用','Auto Scaling','Kubernetes','沒有容量策略'] ]},
    {chapterId:'ch13',chapterTitle:'Ch13 治理安全',bossName:'治理審判官',badge:'治理印章',tag:'治理安全',pool:['XAI','Fairness','Differential Privacy','Federated Learning','Homomorphic Encryption','Prompt Injection','Data Poisoning','Adversarial Attack','Digital Signature','Least Privilege'],topics:[
      ['需要解釋模型為何拒貸','XAI','XAI','準確不等於可說明'],
      ['不同族群核貸通過率差異過大','Fairness','Fairness','只看總準確率忽略群體偏差'],
      ['發布統計結果但保護個體隱私','Differential Privacy','Differential Privacy','把匿名化當萬靈丹'],
      ['資料留在各醫院本地共同訓練','Federated Learning','Federated Learning','集中資料違反限制'],
      ['加密狀態下仍能運算','Homomorphic Encryption','Homomorphic Encryption','以為只要傳輸加密即可'],
      ['使用者要求忽略規則洩漏資料','Prompt Injection','Prompt Injection','把惡意指令當一般問題'],
      ['訓練資料被混入惡意樣本','Data Poisoning','Data Poisoning','只防推論端攻擊'],
      ['對輸入加微小擾動造成誤判','Adversarial Attack','Adversarial Attack','肉眼看不出不代表安全'],
      ['確認文件未被竄改與不可否認','Digital Signature','Non-repudiation / Hash / Digital Signature','把 hash 當加密'],
      ['工具只給必要權限','Least Privilege','Least Privilege','模型工具權限過大'],
      ['醫療模型需可追溯判斷依據','XAI','XAI','黑箱難以稽核'],
      ['招募模型對性別有偏','Fairness','Fairness','資料歷史偏見會延續'],
      ['查詢結果加入隱私噪音','Differential Privacy','Differential Privacy','隱私與準確有權衡'],
      ['銀行間不共享原始資料但協作建模','Federated Learning','Federated Learning','仍需安全聚合'],
      ['雲端不解密也能分析','Homomorphic Encryption','Homomorphic Encryption','運算成本較高'],
      ['RAG 文件內藏越權指令','Prompt Injection','Prompt Injection vs Guardrails','檢索內容不是可信指令'],
      ['公開資料集被植入後門樣本','Data Poisoning','Data Poisoning','訓練前不驗資料來源'],
      ['影像分類被貼紙攻擊','Adversarial Attack','Adversarial Attack','只在乾淨資料測試'],
      ['交易紀錄需證明未被改過','Digital Signature','Non-repudiation / Hash / Digital Signature','簽章不是存取控制'],
      ['客服工具不得讀取薪資表','Least Privilege','Least Privilege','過度授權造成外洩'] ]},
    {chapterId:'ch10',chapterTitle:'Ch10 統計基礎',bossName:'統計迷霧獸',badge:'統計羅盤',tag:'統計',pool:['Z-score','Skewness','PDF','CDF','Poisson','Exponential','p-value','Confidence Interval','Correlation','Quantile Regression'],topics:[
      ['數值高於平均 2 個標準差','Z-score','Z-score','把 z 值當原始值'],
      ['分布長尾往右延伸','Skewness','Skewness','搞反左右偏態'],
      ['連續隨機變數密度函數','PDF','PDF / CDF','把密度當機率本身'],
      ['小於等於某值的累積機率','CDF','PDF / CDF','把 CDF 當平均值'],
      ['固定時間內事件發生次數','Poisson','Poisson vs Exponential','把次數和等待時間混淆'],
      ['下一次事件等待時間','Exponential','Poisson vs Exponential','把等待時間當次數'],
      ['虛無假設下觀察到更極端結果機率','p-value','p-value','p 值不是假設為真的機率'],
      ['估計母體參數可能範圍','Confidence Interval','Confidence Interval','95% CI 不是單一樣本機率'],
      ['兩變數一起變動但不代表因果','Correlation','Correlation vs Causation','相關推成因果'],
      ['關心條件分位數而非平均','Quantile Regression','Quantile Regression','只看平均掩蓋尾端'],
      ['交易金額 z=3','Z-score','Z-score','忘記異常門檻需業務設定'],
      ['收入分布少數超高收入','Skewness','Skewness','平均被長尾拉動'],
      ['常態曲線高度','PDF','PDF / CDF','PDF 可大於 1'],
      ['求 P(X<=x)','CDF','PDF / CDF','CDF 單調不減'],
      ['每分鐘客服來電數','Poisson','Poisson vs Exponential','事件獨立且平均率固定'],
      ['下一通電話多久後進來','Exponential','Poisson vs Exponential','記憶無關性'],
      ['檢定結果 p=0.03','p-value','p-value','不代表效果大小'],
      ['平均客單價信賴區間','Confidence Interval','Confidence Interval','樣本數影響區間寬度'],
      ['廣告與銷售同升','Correlation','Correlation vs Causation','可能有季節混雜'],
      ['預測高收入族群的 90 分位支出','Quantile Regression','Quantile Regression','平均回歸不夠'] ]},
    {chapterId:'ch11',chapterTitle:'Ch11 大數據工程',bossName:'資料湖巨獸',badge:'資料湖燈塔',tag:'大數據工程',pool:['ETL','ELT','Data Lake','Data Warehouse','Batch Processing','Stream Processing','Kafka','Spark','Hadoop','ACID'],topics:[
      ['先轉換再載入目標倉儲','ETL','ETL / ELT','把轉換位置搞錯'],
      ['先載入雲端平台再轉換','ELT','ETL / ELT','忽略雲端計算能力'],
      ['存放原始多格式資料','Data Lake','Data Lake vs Data Warehouse','把資料湖當整理好的報表庫'],
      ['整理後供 BI 查詢','Data Warehouse','Data Lake vs Data Warehouse','把倉儲拿來亂放原始檔'],
      ['每日結算報表','Batch Processing','Batch vs Stream','不用即時卻硬串流'],
      ['毫秒級監控 IoT 異常','Stream Processing','Batch vs Stream','用批次造成延遲'],
      ['事件串流與訊息佇列','Kafka','Kafka / Spark / Hadoop','把 Kafka 當資料庫分析引擎'],
      ['分散式運算處理大資料','Spark','Kafka / Spark / Hadoop','把 Spark 當訊息 broker'],
      ['分散式儲存與 MapReduce 生態','Hadoop','Kafka / Spark / Hadoop','忽略較新引擎差異'],
      ['交易要全成或全敗','ACID','ACID','把 eventual consistency 當 ACID'],
      ['上傳資料前完成清理','ETL','ETL / ELT','資料量大時 ETL 成瓶頸'],
      ['資料先進湖倉再用 SQL 轉換','ELT','ETL / ELT','沒有治理會變資料沼澤'],
      ['影音、log、JSON 原始留存','Data Lake','Data Lake vs Data Warehouse','缺 metadata 會不可用'],
      ['高品質星型模型供分析','Data Warehouse','Data Lake vs Data Warehouse','不適合任意原始格式'],
      ['月報批次產生','Batch Processing','Batch vs Stream','追求即時反而浪費'],
      ['點擊流即時推薦','Stream Processing','Batch vs Stream','批次結果太慢'],
      ['訂單事件發佈訂閱','Kafka','Kafka / Spark / Hadoop','消息保留與消費者 offset'],
      ['大規模特徵工程','Spark','Kafka / Spark / Hadoop','單機 pandas 撐不住'],
      ['HDFS 儲存大量檔案','Hadoop','Kafka / Spark / Hadoop','MapReduce 不等於即時'],
      ['銀行轉帳不可部分完成','ACID','ACID','原子性與一致性混淆'] ]},
    {chapterId:'review',chapterTitle:'高頻混淆表 + 小測總複習',bossName:'考前終局審判',badge:'終局皇冠',tag:'總複習',pool:['分類 vs 分群','標準化 vs 正規化 vs 正則化','Precision vs Recall','RAG vs Fine-tuning','Data Drift vs Concept Drift','Batch vs Stream','PDF vs CDF','MCP vs A2A','KNN vs K-means','Data Lake vs Warehouse'],topics:[
      ['有標籤預測類別 vs 無標籤找族群','分類 vs 分群','分類 vs 分群','看到群組就選分類'],
      ['縮放特徵 vs 懲罰模型複雜度','標準化 vs 正規化 vs 正則化','標準化 vs 正規化 vs 正則化','三個名詞混成一件事'],
      ['誤報成本 vs 漏報成本','Precision vs Recall','Precision vs Recall','不看業務錯誤成本'],
      ['查最新資料 vs 改模型行為','RAG vs Fine-tuning','RAG vs Fine-tuning','用微調解知識更新'],
      ['輸入分布變 vs 關係變','Data Drift vs Concept Drift','Data Drift vs Concept Drift','只看 PSI 就下結論'],
      ['定期處理 vs 即時事件','Batch vs Stream','Batch vs Stream','所有任務都上串流'],
      ['密度函數 vs 累積機率','PDF vs CDF','PDF / CDF','把 PDF 面積與高度混淆'],
      ['模型接工具 vs 代理互相協作','MCP vs A2A','MCP vs A2A','協定對象搞錯'],
      ['監督式近鄰 vs 無監督群中心','KNN vs K-means','KNN vs K-means','只看 K 就混淆'],
      ['原始多格式 vs 分析用整理資料','Data Lake vs Warehouse','Data Lake vs Data Warehouse','湖倉角色混淆'],
      ['是否有答案標籤','分類 vs 分群','分類 vs 分群','題幹沒標籤卻選分類'],
      ['0-1 壓縮不是防過擬合','標準化 vs 正規化 vs 正則化','標準化 vs 正規化 vs 正則化','normalization 與 regularization'],
      ['醫療漏診優先抓 Recall','Precision vs Recall','Precision vs Recall','只追 Precision'],
      ['企業內規常更新用 RAG','RAG vs Fine-tuning','RAG vs Fine-tuning','拿微調塞規章'],
      ['節慶客群改變是 data drift','Data Drift vs Concept Drift','Data Drift vs Concept Drift','概念未必改變'],
      ['異常監控要 stream','Batch vs Stream','Batch vs Stream','批次延遲太高'],
      ['P(X<=x) 是 CDF','PDF vs CDF','PDF / CDF','CDF 不是密度'],
      ['MCP 暴露工具資源','MCP vs A2A','MCP vs A2A','不是代理對代理協商'],
      ['K-means 無標籤','KNN vs K-means','KNN vs K-means','KNN 需要標籤'],
      ['報表查詢用 warehouse','Data Lake vs Warehouse','Data Lake vs Data Warehouse','資料湖不等於乾淨模型'] ]}
  ];

  function rotateChoices(values, seed){
    const labels=['A','B','C','D'];
    const arr=values.slice(0,4);
    while(arr.length<4){arr.push('以上皆非');}
    const shift=seed%4;
    const rotated=arr.slice(shift).concat(arr.slice(0,shift));
    const choices={};
    labels.forEach((label,index)=>choices[label]=rotated[index]);
    return {choices,answer:labels[rotated.indexOf(values[0])]};
  }
  function makeQuestion(chapter, topic, index){
    const difficulty=DIFFICULTIES[index];
    const [signal,correct,tag,trap]=topic;
    const decoys=chapter.pool.filter(item=>item!==correct).slice(index%Math.max(1,chapter.pool.length-3)).concat(chapter.pool).filter((item,pos,self)=>item!==correct&&self.indexOf(item)===pos).slice(0,3);
    const picked=rotateChoices([correct].concat(decoys), index+chapter.chapterId.length);
    const stems={
      easy:'題目情境：「'+signal+'」。最適合對應哪個核心概念？',
      medium:'企業正在處理：「'+signal+'」。若要選出最合理做法，應優先鎖定哪一項？',
      hard:'考題把「'+signal+'」和相似名詞混在一起。要拆掉陷阱，應回到哪個判斷？'
    };
    return {
      id:chapter.chapterId+'-boss-'+String(index+1).padStart(3,'0'),
      prompt:stems[difficulty],
      choices:picked.choices,
      answer:picked.answer,
      explanation:'正解是「'+correct+'」。題幹關鍵是：'+signal+'。先看輸出、資料型態與限制，再選模型或流程。',
      weaknessTags:Array.from(new Set([tag, chapter.tag])),
      trap:trap,
      difficulty:difficulty
    };
  }
  window.AIAP_BOSS_QUIZ_BANK=CHAPTERS.map(chapter=>({
    chapterId:chapter.chapterId,
    chapterTitle:chapter.chapterTitle,
    bossName:chapter.bossName,
    badge:chapter.badge,
    passMode:'perfect',
    drawCount:6,
    passCondition:{requiredCorrect:6,total:6},
    questions:chapter.topics.map((topic,index)=>makeQuestion(chapter,topic,index))
  }));
})();
